services:
  web:
    build:
      context: ./gameStore
      dockerfile: Dockerfile
    container_name: myshop-web
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    volumes:
      - ./gameStore:/var/www/html    # <-- mount local folder for live updates

  db:
    image: postgres:15
    container_name: myshop-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./gameStore/db-init:/docker-entrypoint-initdb.d

volumes:
  db_data:
    name: myshop-db-data
